Debug: false
Format:
  Date: "yyyy-MM-dd HH;mm;ss"
  # Auto: Try to auto-detect best configuration.
  # 3: ANSI 3. 8 colors supported.
  # 4: ANSI 4. 16 colors supported.
  # 8: ANSI 8. 256 colors supported.
  # 24: ANSI 24. RBG value supported.
  ANSI: auto
Loggers:
  File:
    Path: "[CP]/logs/[Config(Loggers.File.Name)].txt"
    Name: "log-[date]"
    MaxSize: "16Kib"
    AtMaxSizeMoveTo: "[CP]/logs/backups/"
    Backup:
      Enable: true
      Type: "Size" # Time
      Size: "16Kib" # Time: 12h
      Path: "[CP]/logs/backups/[Config(Loggers.File.Name)].zip"